FileCreateError
Python 3.9.8: F:\File_my\Project\Plug-in_1\Pyqt\venv64\Scripts\python.exe
Sat May 21 19:10:08 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 F:\File_my\Project\Plug-in_1\Pyqt\designerFile\index.py in ImportLoadData(self=<designerFile.index.MyMainForm object>)
  299             else:
  300                 if re.search('.csv', filename):
  301                     xlsxname = csv_to_xlsx(os.path.join(globalData.cacheFilepath, 'cache'), filenames[0])
  302                     globalData.LoadDatapath = os.path.join(globalData.cacheFilepath, 'cache', xlsxname).replace(
  303                         "\\",
xlsxname undefined
global csv_to_xlsx = <function csv_to_xlsx>
global os = <module 'os' from 'C:\\Users\\kif_win10\\AppData\\Local\\Programs\\Python\\Python39\\lib\\os.py'>
os.path = <module 'ntpath' from 'C:\\Users\\kif_win10\\App...cal\\Programs\\Python\\Python39\\lib\\ntpath.py'>
os.path.join = <function join>
global globalData = <class 'designerFile.index.globalData'>
globalData.cacheFilepath = ''
filenames = ['F:/File_my/Project/Plug-in_1/file/测试文件/Test1/载荷数据.csv']

 F:\File_my\Project\Plug-in_1\Pyqt\designerFile\tools\tools.py in csv_to_xlsx(filepath='cache', csvPath='F:/File_my/Project/Plug-in_1/file/测试文件/Test1/载荷数据.csv')
  155                 r = r + 1
  156             l = l + 1
  157     workbook.close()
  158     return xlsxname
  159 
workbook = <xlsxwriter.workbook.Workbook object>
workbook.close = <bound method Workbook.close of <xlsxwriter.workbook.Workbook object>>

 F:\File_my\Project\Plug-in_1\Pyqt\venv64\lib\site-packages\xlsxwriter\workbook.py in close(self=<xlsxwriter.workbook.Workbook object>)
  324                 self._store_workbook()
  325             except IOError as e:
  326                 raise FileCreateError(e)
  327             except LargeZipFile:
  328                 raise FileSizeError("Filesize would require ZIP64 extensions. "
global FileCreateError = <class 'xlsxwriter.exceptions.FileCreateError'>
e undefined
FileCreateError: [Errno 2] No such file or directory: 'cache\\Load_ IterationN2022-05-21-084392.xlsx'
    __cause__ = None
    __class__ = <class 'xlsxwriter.exceptions.FileCreateError'>
    __context__ = FileNotFoundError(2, 'No such file or directory')
    __delattr__ = <method-wrapper '__delattr__' of FileCreateError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of FileCreateError object>
    __doc__ = 'IO error when creating xlsx file.'
    __eq__ = <method-wrapper '__eq__' of FileCreateError object>
    __format__ = <built-in method __format__ of FileCreateError object>
    __ge__ = <method-wrapper '__ge__' of FileCreateError object>
    __getattribute__ = <method-wrapper '__getattribute__' of FileCreateError object>
    __gt__ = <method-wrapper '__gt__' of FileCreateError object>
    __hash__ = <method-wrapper '__hash__' of FileCreateError object>
    __init__ = <method-wrapper '__init__' of FileCreateError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of FileCreateError object>
    __lt__ = <method-wrapper '__lt__' of FileCreateError object>
    __module__ = 'xlsxwriter.exceptions'
    __ne__ = <method-wrapper '__ne__' of FileCreateError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of FileCreateError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of FileCreateError object>
    __repr__ = <method-wrapper '__repr__' of FileCreateError object>
    __setattr__ = <method-wrapper '__setattr__' of FileCreateError object>
    __setstate__ = <built-in method __setstate__ of FileCreateError object>
    __sizeof__ = <built-in method __sizeof__ of FileCreateError object>
    __str__ = <method-wrapper '__str__' of FileCreateError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    __weakref__ = None
    args = (FileNotFoundError(2, 'No such file or directory'),)
    with_traceback = <built-in method with_traceback of FileCreateError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "F:\File_my\Project\Plug-in_1\Pyqt\venv64\lib\site-packages\xlsxwriter\workbook.py", line 324, in close
    self._store_workbook()
  File "F:\File_my\Project\Plug-in_1\Pyqt\venv64\lib\site-packages\xlsxwriter\workbook.py", line 659, in _store_workbook
    raise e
  File "F:\File_my\Project\Plug-in_1\Pyqt\venv64\lib\site-packages\xlsxwriter\workbook.py", line 656, in _store_workbook
    xlsx_file = ZipFile(self.filename, "w", compression=ZIP_DEFLATED,
  File "C:\Users\kif_win10\AppData\Local\Programs\Python\Python39\lib\zipfile.py", line 1239, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'cache\\Load_ IterationN2022-05-21-084392.xlsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\File_my\Project\Plug-in_1\Pyqt\designerFile\index.py", line 301, in ImportLoadData
    xlsxname = csv_to_xlsx(os.path.join(globalData.cacheFilepath, 'cache'), filenames[0])
  File "F:\File_my\Project\Plug-in_1\Pyqt\designerFile\tools\tools.py", line 157, in csv_to_xlsx
    workbook.close()
  File "F:\File_my\Project\Plug-in_1\Pyqt\venv64\lib\site-packages\xlsxwriter\workbook.py", line 326, in close
    raise FileCreateError(e)
xlsxwriter.exceptions.FileCreateError: [Errno 2] No such file or directory: 'cache\\Load_ IterationN2022-05-21-084392.xlsx'

